func f1() {
  print("f1");
  return 1;
}

func f2() {
  print("f2");
  return 2;
}

func f3() {
  print("f3");
  return 3;
}

func fe() {
  print("fe");
  raise "ferr";
  print("must not print");
  return nil;
}

func main() {
  var x;
  x = f1() + f2() + f3() + f2() + f1() + f2() + f3() + fe() + f2() + f3() + f4() + f5() + f6();
  print("no error yet");
  try {
    print("inside try");
    print(x);
    print("post try error. must not print");
  }
  catch "ferr" {
    x = f1() + f3() + f3() + f2() + f2() + f3()+ f1();
    print(x);
    print("ferr was caught");
  }
  print(x + 3);
  print("exit");
}

/*
*OUT*
no error yet
inside try
f1
f2
f3
f2
f1
f2
f3
fe
f1
f3
f3
f2
f2
f3
f1
15
ferr was caught
18
exit
*OUT*
*/